use gxoa;

drop table gx_m_user;
drop table gx_m_roles;
drop table gx_m_permission;
drop table gx_m_staff;
drop table gx_m_dept;
drop table GX_M_USER_ROLES;
drop table GX_M_ROLE_PERMISSIONS;
drop table GX_M_MODULES;
drop table GX_M_MODULES_PERMISSIONS;

--用户表
CREATE TABLE GX_M_USER (
	USER_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	USERNAME NVARCHAR(50) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(50) NOT NULL,
	STAFF_ID CHAR(6) NOT NULL UNIQUE,
	LAST_LOGIN_DT DATETIME,
	REMARK NVARCHAR(100),
);

--【角色表】
CREATE TABLE GX_M_ROLES (
	ROLE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ROLE_CD NVARCHAR(50) NOT NULL UNIQUE,
	ROLE_NAME NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);

--【用户-角色表】
CREATE TABLE GX_M_USER_ROLES (
	USER_ROLES_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	USERNAME NVARCHAR(50) NOT NULL,
	ROLE_CD NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);

--【权限表】
CREATE TABLE GX_M_PERMISSIONS (
	PERM_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PERM_CD NVARCHAR(50) NOT NULL UNIQUE,
	PERM_NAME NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);

--【模块表】
CREATE TABLE GX_M_MODULES (
	MODU_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MODU_CD NVARCHAR(50) NOT NULL UNIQUE,
	MODU_NAME NVARCHAR(50) NOT NULL,
	PARENT_MODU_CD NVARCHAR(50),
	REMARK NVARCHAR(100),
);

--【模块权限表】
CREATE TABLE GX_M_MODULES_PERMISSIONS (
	MODU_PERM_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MODU_CD NVARCHAR(50) NOT NULL,
	PERM_CD NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);

--【角色-权限表】
CREATE TABLE GX_M_ROLE_PERMISSIONS (
	ROLE_PERM_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ROLE_CD NVARCHAR(50) NOT NULL,
	MODU_PERM_ID NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);


--【员工信息表】
CREATE TABLE GX_M_STAFF (
	STAFF_ID CHAR(6) NOT NULL PRIMARY KEY,
	FAMILY_NAME NVARCHAR(50),
	SEX CHAR(1),
	BIRTHDAY DATE,
	DEGREE VARCHAR(50),
	DUTY VARCHAR(50),
	PHONE_NO VARCHAR(11),
	EMAIL VARCHAR(50),
	DEPT_ID CHAR(4) NOT NULL,
	REMARK NVARCHAR(100),
);

--【部门信息表】
CREATE TABLE GX_M_DEPT (
	DEPT_ID CHAR(4) NOT NULL PRIMARY KEY,
	DEPT_NAME NVARCHAR(50) NOT NULL,
	REMARK NVARCHAR(100),
);



use gxoa;
update GX_M_USER set PASSWORD = upper(right(sys.fn_VarBinToHexStr(hashbytes('MD5','********1')),32))
where USER_ID = 1;
update GX_M_USER set PASSWORD = upper(right(sys.fn_VarBinToHexStr(hashbytes('MD5','********2')),32))
where USER_ID = 2;
update GX_M_USER set PASSWORD = upper(right(sys.fn_VarBinToHexStr(hashbytes('MD5','********3')),32))
where USER_ID = 3;

select right(sys.fn_VarBinToHexStr(hashbytes('MD5','123456')),32);